---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: pal-tracker-tap
  name: pal-tracker-tap
  namespace: default
spec:
  env:
  - name: WELCOME_MESSAGE
    value: Hello from TAP (environment)
  params:
  - name: tekton-pipeline-name
    value: pal-tracker-pipeline
  source:
    git:
      ref:
        branch: main
      url: https://github.com/ndwinton/pal-tracker-tap
